# CommunicationSocket
SW_SIZE = 1
SR_SIZE = 32

# packet
MAX_PACKET_SIZE = 1280
LEN_LENGTH = 2
SEQNUM_LENGTH = 3
TYPE_LENGTH = 1
LEN_POS = 0
TYPE_POS = LEN_LENGTH
SEQNUM_POS = TYPE_POS + TYPE_LENGTH
DATA_POS = SEQNUM_POS + SEQNUM_LENGTH

# SocketListener
HOST_DEFAULT = "127.0.0.1"

# Packet Orchestrator
SYN_SEQ_NUM = 0
TIMEOUT_LIMIT = 0.05
MAX_TRIES = 100

# PacketReceiver
MAX_BUFFER_SIZE = 1024
TIMEOUT_LIMIT = 0.05
TIMEOUT_RECVFROM = 1
